apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      name: my-web-app
  replicas: 3
  template:
    metadata:
      labels:
        name: my-web-app
    spec:
      containers:
      - name: myapp
        image: mustafahagras/hagras
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
